spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zk_mysql
    username: root
    password: zk124trying
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
